### ISSUE TITLE
Please consider supporting optimization of metaparamers

### ISSUE THREAD

**Issue by NeilGirdhar** [deepmind/optax#1]
This is a very exciting project!  I was just considering using flax.optim when I found optax, and I love the elegant `combine.chain` design of the varias optimizer aliases.  Very cool!

I'd like to consider learning as an iterated function of the parameters, which itself depends on meta-parameters (e.g. learning rate).  Then, I can use the fixed point theorem to calculate the gradient of the loss on a batch with respect to the metaparameters.

Unfortunately, optax's `GradientTransformations` are implemented using functions that _close over values_, which means that these values cannot be JAX tracers.  From my understanding, you cannot take the derivative with respect to the `step_size` if the step size is a closed-over-value.

I know this might be a serious change, but would it be possible, instead of having:
```python
def scale(step_size: float) -> GradientTransformation:
  ...
  return GradientTransformation(init_fn, update_fn)
```

To implement the abstract methods `init_fn` and `update_fn` in an inherited class:
```python
class Scale(GradientTransformation):
  def __init__(self, step_size):
    ...
```

This design would allow:
- taking derivatives with respect to various meta-parameters (like `step_size`),
- inspecting objects (`scale.step_size` is available in the object oriented approach) for debugging,
- comparing objects and preventing recompilation of jitted functions.  If, for some reason, you call `scale(1e-3)` twice, you get a different object each time, and these objects will not compare equal.  If these objects are passed to a jitted function, the function will be recompiled even though the objects would normally be equal.

**Comment by NeilGirdhar** [comment]
Actually, I'll just use it as is, and if I run into this problem, I'll either reopen this issue or build a shim around optax with a more object oriented design.

**Comment by mtthss** [comment]
Hi Neil,

Meta-gradients are definitely something that is very close to my heart,
As I have been using optax in a number of recent MG papers
E.g. https://arxiv.org/abs/2007.08794, https://arxiv.org/abs/2007.08433

You will find that many of the building blocks in optax are carefully crafted to ensure that they are suitable for meta-gradients (including subtle numerical issues; see for instance the eps_root argument in `scale_by_adam` - only important if you want to backprop through an update - or the specific implementation of `clip_by_norm` - also carefully written to support back propping through it).

Regarding your specific query, here is how I would implement meta-learning of a global learning rate
(written quickly just to give the idea)

```
optim = optax.chain(optax.clip_by_global_norm(10.), optax.scale_by_adam())
meta_optim = optax.chain(optax.clip_by_global_norm(0.1), optax.scale_by_adam())

def inner_update(theta, theta_opt_state, eta, batch):
  """Perform a step of inner update to the agent."""
  grads = jax.grad(inner_loss)(theta, batch)
  updates, new_theta_opt_state = optim.apply(grads, theta_opt_state)
  scaled_updates = tree_map(lambda t: eta * t, updates)
  new_theta = optax.apply_updates(theta, updates)
  return new_theta, new_theta_opt_state

def inner_updates_and_outer_loss(eta, theta, theta_opt_state, rollout_arr):
  """Perform a few inner updates and then compute validation loss."""
  for batch in batches[:-1]:
    theta, theta_opt_state = self.inner_update(theta, theta_opt_state, eta, batch)
 loss = self.outer_loss(theta,  batches[-1])
 return loss, (theta, theta_opt_state)

def update(theta, theta_opt_state, eta, eta_opt_state, batches):
  """Update params(theta) and meta-params (eta)."""
  (new_theta, new_theta_opt_state), meta_grads = jax.grad(inner_updates_and_outer_loss, has_aux=True)(
      eta, theta, theta_opt_state, batches)
  eta_updates, new_eta_opt_state = meta_optim.apply(meta_grads, eta_opt_state)
  new_eta = optax.apply_updates(eta, eta_updates)
  return (new_theta, new_theta_opt_state, new_eta, new_eta_opt_state)
```

It would be possible to abstract some of this away into a suitable meta-gradient / meta-learning library built on top of optax, and I would be excited to see that! The aim of optax is to provide the shared, low level, well tested, flexible building blocks,
that the community can use to construct such (and many other) higher level libraries. By keeping optax fairly slim we can ensure we can reuse these building blocks across many higher-level libraries, therefore sharing effort and code.

**Comment by NeilGirdhar** [comment]
@mtthss Thank you, yes.  What I was trying to explain is that when you go to calculate `ax.grad(inner_updates_and_outer_loss...`, this depends on `inner_update`, which depends on `optim`, which closes over parameters like learning rates.  This means that your gradient can easily result in leaked tracers in JAX.

Leaked tracers have cost me weeks of debugging time, and now I'm extremely wary of closing over tracers.  That's why I prefer the object oriented design I suggested so that the objects can be registered as pytrees and this problem is avoided.

**Comment by mtthss** [comment]
> Did you forget a minus sign in scaled_updates?
Yes, in my defence I did write that code in less than 5 minutes,
its more meant to be pseudo-code than actual runnable Python :)

The approach above is not specific to eta being just a learning rate, e.g. I have used to backprop through optax updates to meta-learn all hyper-parameters of complex RL loss functions (eta = {gamma, lambda, baseline_cost, entropy_cost, ...}), or even the entire loss function in the inner update (eta = {parameters of a neural network}).

However, I do see better your point now, in that while I can back-prop *through* the gradient transformations into any hyper-param of the inner loss (my typical setting), the hyper-parameters of the gradient transform *itself* are not natively exposed to meta-gradients, unless you break them out as I did for the learning rate.

I would be quite interested in seeing an object oriented meta-gradient design for a `meta-optax` extension library, that is compatible with the optax API (e.g. each GradientTransformation offers the init/apply public methods, and thus is compatible and chainable to standard optax transforms) but whose transforms allow to expose the hyper-parameters of the transformations themselves to meta-learning.

**Comment by NeilGirdhar** [comment]
> I would be quite interested in seeing an object oriented design for a meta-optax extension library, 

What do you think of [this](https://github.com/NeilGirdhar/tjax/blob/master/tjax/gradient_transformation.py)?  I'm still working on the design to get it to fit with my project.

**Comment by mtthss** [comment]
That's a good start, a major thing that I would strongly suggest is that you switch the method names to the signature of `GradientTramsformation` in `optax`. Then your transformations would be immediately interoperable with `optax` natives transformations. The `init`/`update` is also somewhat canonical across several other JAX libraries as well. Looking forward to see further iterations of this.

Few other smaller points:
1. Instead of defining your own `dataclass`, why not use the `dataclass` defined in the `chex` library?
2. Some of the type annotation you define in your codebase are also defined in the `chex` library (and a couple others could maybe be upstreamed there?). In the Tensor annotation btw the Union is superflous, see for instance `chex.Array`

**Comment by mtthss** [comment]
I do like of the design how it manages to build the support for meta-gradients on top of the existing optax low level components. If in addition you make sure the transformations are interoperable it would be really quite cool.

**Comment by mtthss** [comment]
One interesting thing is that the dataclass structure for Scale and ScaleByAdam is actually exactly the same (modulo which optax transformation is wrapped). I actually wonder if we could even implement this as a generic wrapper, that takes an arbitrary optax transformation and allows to inject the arguments according to the pattern from your code.

**Comment by NeilGirdhar** [comment]
> That's a good start, a major thing that I would strongly suggest is that you switch the method names to the signature of GradientTramsformation in optax. Then your transformations would be immediately interoperable with optax natives transformations. The init/update is also somewhat canonical across several other JAX libraries as well.

Oh, I didn't realize that!  Okay, that's pretty convincing.

> Instead of defining your own dataclass, why not use the dataclass defined in the chex library?

The main reason is that I updated the dataclass mypy plugin so that it understands the `replace` method and its arguments: [plugin](https://github.com/NeilGirdhar/cooperative_dataclasses/blob/master/cooperative_dataclasses/mypy_plugin.py).  It also supports inheritance with regular mixins and classes, but I've never actually used that.

> Some of the type annotation you define in your codebase are also defined in the chex library (and a couple others could maybe be upstreamed there?)

Nice!  I'll just use your types where I can and update my codebases.  Feel free to upstream whatever you like.  I guess that one day JAX will be able to use [`Annotated`](https://www.python.org/dev/peps/pep-0593/) to promise real (non-complex) `Array` types.

> I actually wonder if we could even implement this as a generic wrapper, that takes an arbitrary optax transformation and allows to inject the arguments according to the pattern from your code.

Yes, I also considered that.  I don't know how to lift out the parameters to `scale_by_adam` and create member variables out of them.  I guess that it's possible with inspection, but I just wanted to see if I could fit this interface into my larger project.

> Looking forward to see further iterations of this.

Perhaps you could help me with some design?  I've been thinking about how to get the meta-learning working, and right now the way it's done is to take the gradient with respect to the objects of type, say, `Scale`, `ScaleByAdam`, etc.  This works fine as long as I want the gradient with respect to every meta-parameter, and it works so long as these objects only contain real values.  But what if there is some Boolean flag, or integer component?  Then, this approach won't work.  What are your thoughts on this?

My first thought is to pass in some kind of magic `MetaParameter` object for the parameters that I want to be meta-parameters.  These would contain a name.  Then, then when I call `update`, I would send a mapping from names to values, and the meta-parameters would be looked up by name and filled in.  In practice, JAX could calculate gradients with respect to these values (I guess they would be JAX tracers).  What do you think?

**Comment by NeilGirdhar** [comment]
(Not sure why I closed this).

**Comment by mtthss** [comment]
Adding an optional meta_params is definitely one option. For the main library I am probably still going to look into having a generic wrapper that allows to lifts the hyper-params of an arbitrary transform and replace it with a traceable array. Since meta-learning is still somewhat niche (although I am very into it myself) I want to make sure we support without making any harder for users to write their own transforms and mix and match them with the existing one. I have some ideas on how this might be done, but I will be away for a couple of weeks, so your approach definitely seems like a reasonable to get you going in the short term.

**Comment by mtthss** [comment]
Does the `inject_hyperparameters` wrapper solve the optimisation of metaparameters?

Since this allows you to feed in updated hyper-parameters on every step, it should also allow to take gradients with respect to these (havn't tested it yet), wdyt?

**Comment by NeilGirdhar** [comment]
@mtthss I don't see the wrapper, but I just use rewrote your transforms as dataclasses: https://github.com/NeilGirdhar/tjax/blob/master/tjax/_src/gradient/transforms.py  Since these are pytrees, I can differentiate with respect to their parameters.

**Comment by mtthss** [comment]
The current approach where hyper-parameters are captured as closure is designed to keep two things separate:

* the definition of the optimiser, statically captured in closures
* the dynamic state of the optimiser, captured in the `opt_state`

The crux is then: how do we enable users who want to make the optimiser's definition dynamic?

One possibility is to drop entirely the distinction between static optimiser definition (captured by closures) and dynamic optimiser state (captured by the opt_state). 

However a second possibility is to preserve this distinction, and instead enable the user who wants to make parts of the optimiser definition dynamic to do so explicitly. How can we do this cleanly and easily? 

Until recently we did not have the right tooling for this. However I think the `inject_hyperparams` wrapper contributed by @n2cholas is exactly the right tool for the job. It enables the user to cleanly and easily prescribe what parts of the optimiser def to make dynamic by just writing things like:

```
opt = optax.inject_hyperparams(optax.adam)(learning_rate=jnp.array(0.1))
```

This is sufficient to allow the user to 
1) compute gradients with respect to the hyper-parameter that was exposed to learning
2) use these gradients to update the hyper-parameter

I think this is the right approach for meta-learning because it preserves the clear separation
between what's static (in closure) and what's dynamic (in the state),
indeed the `inject_hyperparams` works exactly by incorporating the hyper-params as part of `state.hyperparams`.

We put together a complete example for meta-learning an optimiser's hyperparams in the docs
https://optax.readthedocs.io/en/latest/meta_learning.html

Could you take a look and tell us what you think?

**Comment by NeilGirdhar** [comment]
> One possibility is to drop entirely the distinction between static optimiser definition (captured by closures) and dynamic optimiser state (captured by the opt_state).

I think you've misunderstood.  I'm not suggesting that you drop this distinction.  The distinction is good.

I'm merely suggesting that you store the optimizer definition using a pytree rather than a closure.  Jax is horrible with closures.  Pytrees allow vectorization, gradients, and prevent recompilation of jits.

> How can we do this cleanly and easily?

I've already coded this.  Is there any problem with lifting [my code](https://github.com/NeilGirdhar/tjax/blob/master/tjax/_src/gradient/transforms.py) into optax?

> I think this is the right approach for meta-learning because it preserves the clear separation
between what's static (in closure)

I agree that you should definitely preserve this clear separation.  However, what is the benefit of hanging on to closures over dataclasses?

> but sometimes resulted in subtle bugs

Would you mind elaborating?  I've also written a tremendous amount of JAX code, and I haven't seen any drawbacks to using dataclasses.  On the contrary, code that uses dataclasses is easier to read, and has fewer bugs because you always get the static-vs-dynamic question right since it's baked into the dataclass.

> Could you take a look and tell us what you think?

Yeah, it's an interesting tool, but it's not what this issue is about.  The main goal of this issue is in the bulleted list at the top: taking derivatives with respect to parameters of the optimizer.

**Comment by mtthss** [comment]
> I'm not sure it solves the goal of this issue though. The main goal of this issue is in the bulleted list at the top: taking derivatives with respect to parameters of the optimizer.

I am afraid I don't follow, isn't "taking derivatives with respect to parameters of the optimizer." exactly what `inject_hyperparams` enables in this example I shared above?
https://optax.readthedocs.io/en/latest/meta_learning.html

**Comment by NeilGirdhar** [comment]
If you'll indulge me, I'd like to make sure we're on the same page about what static and dynamic means in the context of JAX.  I don't know that it's really well explained anywhere, and it's something that it's easy to misunderstand.

Dynamic JAX objects must be "JAX types", which means numbers, arrays.  When passed to the JIT, they form the arguments to the compiled program.  Calling the jitted function with different values for the dynamic parameters never induces recompilation.  Dynamic parameters can be vectorized by `vmap`, and be the differentiand of `grad`, `vjp`, `jvp`, etc.

Static JAX objects must be hashable.  When passed to the JIT, they are used as a key when looking up the compiled program.  Calling the jitted function with different values for the static parameters always induces recompilation.  Static parameters cannot be vectorized or be the differentiand.  However, static parameters have their values available in the JIT code, so they can be used in Python switches like `if` and `while`.

Pytrees are either an aggregate objects comprising pytrees, dynamic fields, and static fields, or else purely dynamic JAX objects.

Everything that's passed to a jitted function is either marked as entirely static, or else is a pytree.

> We now have a mixed entity that includes both static and dynamic state outside of the state.

I don't see a problem with having aggregate types that are "a mixed entity that includes both static and dynamic state".  This is exactly what pytrees are meant to handle.

Also, it seems that you're implying (forgive me if I'm misunderstanding you) that because the optimizer definition doesn't usually take on different values, it should be "static".  This is not what static means in a JAX context.  The main reasons to make something static are because it is not a JAX type or you need to switch on its value within the JIT.

>  I could easily see a user forgetting to mark something as static.

The user isn't the person marking the fields as static and dynamic.  That would be done within optax since that's where the classes are defined.

And if you're worried about getting it wrong, your tests should catch any mistakes:  If a dynamic array-valued field is accidentally marked static, JAX will complain ("not a JAX type").  If a field you switch on is accidentally marked dynamic, JAX will complain ("concrete value is expected").  If you accidentally mark a numerical field that should be dynamic as static, it won't cause any bugs, but your users will eventually complain about recompilation or inability to vectorize over that field.

> I understand there is also the other issue you raised, and stylistical preferences that might edge us one way or the other,
but lets first be clear as to whether the optimisation of metaparameters itself is solved in my example.

Yes, it is definitely one approach.  However, if you had just made the transformation a pytree, you wouldn't need `inject_hyperparams` at all:

```python
from typing import Iterator, Tuple
import chex
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
import optax
from tjax.gradient import rmsprop

def generator() -> Iterator[Tuple[chex.Array, chex.Array]]:
    rng = jax.random.PRNGKey(0)

    while True:
        rng, k1, k2 = jax.random.split(rng, num=3)
        x = jax.random.uniform(k1, minval=0.0, maxval=10.0)
        y = 10.0 * x + jax.random.normal(k2)
        yield x, y

g = generator()

def f(theta: chex.Array, x: chex.Array) -> chex.Array:
    return x * theta

theta = jax.random.normal(jax.random.PRNGKey(42))

init_learning_rate = jnp.array(0.1)
meta_learning_rate = jnp.array(0.03)

opt = rmsprop(learning_rate=init_learning_rate)
meta_opt = optax.adam(learning_rate=meta_learning_rate)

def loss(theta, x, y):
    return optax.l2_loss(y, f(theta, x))

def step(opt, theta, state, x, y):
    grad = jax.grad(loss)(theta, x, y)
    updates, state = opt.update(grad, state, theta)
    theta = optax.apply_updates(theta, updates)
    return theta, state

@jax.jit
def outer_loss(eta, theta, state, samples):
    # If opt is a pytree, it can just be reconstructed and passed to step.
    opt = rmsprop(learning_rate=jax.nn.sigmoid(eta))

    for x, y in samples[:-1]:
        theta, state = step(opt, theta, state, x, y)

    x, y = samples[-1]

    return loss(theta, x, y), (theta, state)

@jax.jit
def outer_step(eta, theta, meta_state, state, samples):
    grad, (theta, state) = jax.grad(
        outer_loss, has_aux=True)(eta, theta, state, samples)

    meta_updates, meta_state = meta_opt.update(grad, meta_state)
    eta = optax.apply_updates(eta, meta_updates)

    return eta, theta, meta_state, state

state = opt.init(theta)
# inverse sigmoid, to match the value we initialized the inner optimizer with.
eta = -np.log(1. / init_learning_rate - 1)
meta_state = meta_opt.init(eta)

N = 7
learning_rates = []
thetas = []

for i in range(2000):
    samples = [next(g) for i in range(N)]
    eta, theta, meta_state, state = outer_step(
        eta, theta, meta_state, state, samples)
    learning_rates.append(jax.nn.sigmoid(eta))
    thetas.append(theta)

fig, (ax1, ax2) = plt.subplots(2)
fig.suptitle('Meta-learning RMSProp\'s learning rate')
plt.xlabel('Step')

ax1.semilogy(range(len(learning_rates)), learning_rates)
ax1.set(ylabel='Learning rate')
ax1.label_outer()

plt.xlabel('Number of updates')
ax2.semilogy(range(len(thetas)), thetas)

ax2.label_outer()
ax2.set(ylabel='Theta')

plt.show()
```

**Comment by mtthss** [comment]
Please refer to the message https://github.com/deepmind/optax/issues/197#issuecomment-982548377 for our proposed resolution of the issue going forward.

**Comment by Waterkin** [comment]
> Hi Neil,
> 
> Meta-gradients are definitely something that is very close to my heart, As I have been using optax in a number of recent MG papers E.g. https://arxiv.org/abs/2007.08794, https://arxiv.org/abs/2007.08433
> 
> You will find that many of the building blocks in optax are carefully crafted to ensure that they are suitable for meta-gradients (including subtle numerical issues; see for instance the eps_root argument in `scale_by_adam` - only important if you want to backprop through an update - or the specific implementation of `clip_by_norm` - also carefully written to support back propping through it).
> 
> Regarding your specific query, here is how I would implement meta-learning of a global learning rate (written quickly just to give the idea)
> 
> ```
> optim = optax.chain(optax.clip_by_global_norm(10.), optax.scale_by_adam())
> meta_optim = optax.chain(optax.clip_by_global_norm(0.1), optax.scale_by_adam())
> 
> def inner_update(theta, theta_opt_state, eta, batch):
>   """Perform a step of inner update to the agent."""
>   grads = jax.grad(inner_loss)(theta, batch)
>   updates, new_theta_opt_state = optim.apply(grads, theta_opt_state)
>   scaled_updates = tree_map(lambda t: eta * t, updates)
>   new_theta = optax.apply_updates(theta, updates)
>   return new_theta, new_theta_opt_state
> 
> def inner_updates_and_outer_loss(eta, theta, theta_opt_state, rollout_arr):
>   """Perform a few inner updates and then compute validation loss."""
>   for batch in batches[:-1]:
>     theta, theta_opt_state = self.inner_update(theta, theta_opt_state, eta, batch)
>  loss = self.outer_loss(theta,  batches[-1])
>  return loss, (theta, theta_opt_state)
> 
> def update(theta, theta_opt_state, eta, eta_opt_state, batches):
>   """Update params(theta) and meta-params (eta)."""
>   (new_theta, new_theta_opt_state), meta_grads = jax.grad(inner_updates_and_outer_loss, has_aux=True)(
>       eta, theta, theta_opt_state, batches)
>   eta_updates, new_eta_opt_state = meta_optim.apply(meta_grads, eta_opt_state)
>   new_eta = optax.apply_updates(eta, eta_updates)
>   return (new_theta, new_theta_opt_state, new_eta, new_eta_opt_state)
> ```
> 
> It would be possible to abstract some of this away into a suitable meta-gradient / meta-learning library built on top of optax, and I would be excited to see that! The aim of optax is to provide the shared, low level, well tested, flexible building blocks, that the community can use to construct such (and many other) higher level libraries. By keeping optax fairly slim we can ensure we can reuse these building blocks across many higher-level libraries, therefore sharing effort and code.

Hi, I tried to use the code above, but got some error:
① Gradient Transformation has no attribute 'apply'
② TypeError: unsupported operand type(s) for *: 'dict' and 'DynamicJaxprTracer' （at `scaled_updates = tree_map(lambda t: eta * t, updates)`）

**Comment by NeilGirdhar** [comment]
@Waterkin It appears your `eta` is a dict.

Anyway, I think the optax is solution is over-complicated.  It's a lot easier to simply use the transformations in `tjax.gradient`, which have all meta-parameters as ordinary dynamic values.

**Comment by Waterkin** [comment]
> @Waterkin It appears your `eta` is a dict.
> 
> Anyway, I think the optax is solution is over-complicated. It's a lot easier to simply use the transformations in `tjax.gradient`, which have all meta-parameters as ordinary dynamic values.

Thanks for your reply, Neil. I'll see if tjax helps.
