### ISSUE TITLE
How to combine parameters from different haiku modules?

### ISSUE THREAD

**Issue by altosaar** [deepmind/optax#128]
In PyTorch, it is possible to have a single optimizer for different `nn.Module` sets of parameters, and there are various ways to combine different modules' parameters. 

For example, from https://github.com/altosaar/variational-autoencoder/blob/dfb452b5421e9e5b97315c6420b8766ac86f3f4f/train_variational_autoencoder_pytorch.py#L216:

    optimizer = torch.optim.RMSprop(        list(model.parameters()) + list(variational.parameters()),        lr=cfg.learning_rate,        centered=True,    )

What is the equivalent in optax? Is it chaining optimizers, or is such functionality not supported at this time, requiring different instances of optax optimizers, one per `haiku.Module`?

Thanks so much!

**Comment by n2cholas** [comment]
Yes, you can simply create a collection combining all your parameters, then pass that to `tx.init`. Below's an example:

```py
import jax.numpy as jnp
import optax

# Suppose the collections below are arbitrary PyTrees with parameters 
# from Haiku (or any other framework)
model_params = {'linear': {'w': jnp.zeros((5, 5)), 'b': jnp.zeros(5)}}
other_params = {'other': jnp.zeros(3)}

# Create another PyTree (here, just a tuple) with all the params
all_params = (model_params, other_params)

tx = optax.rmsprop(learning_rate=0.001, centered=True)
state = tx.init(all_params)

# suppose you have gradients for both
model_param_grads = ...
other_param_grads = ...

# Combine the grads the same way you combined the params
all_param_grads = (model_param_grads, other_param_grads)

# Apply model updates
updates, new_state = tx.update(all_param_grads, state)
new_all_params = optax.apply_updates(all_params, updates)

# Unpack new params as needed
new_model_params, new_other_params = new_all_params
```

How does that sound?

**Comment by altosaar** [comment]
Thank you so much! This is what I was looking for :) and solves the problem nicely!!!

**Comment by rsmath** [comment]
Hi. I need help with this topic. I am using Haiku for creating my neural networks. The parameters for the networks are not training when I am using the approach you mentioned above. Can someone please help me figure out how to properly apply the optimizer updates to the two neural network parameters?

Thank you.

@jaanli @n2cholas

**Comment by n2cholas** [comment]
@rsmath could you send a snippet/gist of code demonstrating the issue? If it is structured like the suggestion above it should work.

**Comment by rsmath** [comment]
I was able to get it work. Thank you for your help :)
