### ISSUE TITLE
Which JAX-based libraries is optax compatible with?

### ISSUE THREAD

**Issue by joaogui1** [deepmind/optax#14]
Sorry for the lazy question, but is optax compatible with [objax](https://github.com/google/objax) or [flax](https://github.com/google/flax/)? Or is it only compatible with haiku?

**Comment by mtthss** [comment]
optax and haiku are fully independent (although interoperable).

optax operates on the gradients and params,
and these may be represented by any arbitrary data structure,
(e.g. dictionaries, tuples, named tuple, nested structs of the above, ...)
anything really, as long as you can operate on them with the native JAX `tree_utils`.

**Comment by joaogui1** [comment]
Great, thanks!
