### ISSUE TITLE
__all__ is currently not useful in __init__.py

### ISSUE THREAD

**Issue by n2cholas** [deepmind/optax#141]
`__all__` in the `__init__.py` overrides which functions are imported when a user does `from optax import *`. It seems like every function in that file should be exposed through a wildcard import, so there is no need for the `__all__`. Besides being redundant, having it creates opportunities for bugs: right now, many of the functions (e.g. `maybe_update`, `keep_params_nonnegative`) are imported but not exposed in `__all__`. I believe it should be removed, and would be happy to create a PR if that makes sense.

**Comment by rosshemsley** [comment]
`__all__` can be a useful way to communicate explicitly the intended public API, and is considered good practice according to [PEP8](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces).

This can help to avoid, for example, leaking global constants declared in `__init__.py` into the public interface.

You raise an interesting point that not all functions have been added to the `__all__`, though. I will look a little further into where this may be intention or not.

**Comment by n2cholas** [comment]
I agree with the motivation in PEP8, and think `__all__`s are useful in other libraries, but I think the situation is different here. Optax already keeps all the source in the private `_src` folder and imports necessary symbols explicitly in `__init__`, which already communicates the intended API and prevents leaking constants, thus makes the `__all__` redundant.
