### ISSUE TITLE
Support specifying end_value for exponential_decay

### ISSUE THREAD

**Issue by n2cholas** [deepmind/optax#21]
It would be convenient to support specifying an `end_value` for exponential decay. So, the `exponential_decay` would require `init_value` and `transition_steps` and one of (`end_value` or `decay_rate`). [Here](https://github.com/tensorflow/kfac/blob/master/kfac/python/keras/callbacks.py#L116) is an example of what I'm proposing. 

I would be happy to contribute this, if you think it is suitable.

**Comment by mtthss** [comment]
I like the idea of adding an `end_value` argument, to support these.

When a decay rate and num_decay_steps is provided:
```
step = min(global_step - num_delay_steps, num_decay_steps)
    decayed_value = init_value * decay_rate^step
```

When a decay_rate and final_value are provided:
```
step = global_step - num_delay_steps
decayed_value = max(init_value * decay_rate^step, final_value)
```

But I would be inclined to keep `decay_rate` compulsory,
and have a check that only of `end_value` and `transtion_steps` is provided.

Does that seem reasonable to you?

**Comment by n2cholas** [comment]
That sounds good @mtthss, I'll make a PR for that! 

The utility function would be pretty trivial:

```python
def exponential_decay_rate(init_value: float, end_value: float, transition_steps: int):
    return (final_value / init_value) ** (1.0 / transition_steps)
```

To be honest, calling this function is about as much code as the computation itself, so I don't think it makes sense to provide it. What do you think?

**Comment by mtthss** [comment]
Good point, and apologies for the confusion, you are absolutely right.
Maybe worth clarifying better in the doc string.

**Comment by n2cholas** [comment]
Great, I'll work on a PR for this. I think the doc string is fine (it shows the update expression), I just didn't read it closely 😅.
