### ISSUE TITLE
Custom_vjp/jvp for parameter update functions

### ISSUE THREAD

**Issue by pharringtonp19** [deepmind/optax#247]
In some examples of bi-level optimization, like maml, we want to differentiate the parameter update function.

Is it possible to write custom_vjp/jvps for these update functions? -- Thanks

**Comment by mtthss** [comment]
Could you elaborate on what exactly you want to differentiate?
Most likely you don't even need to write custom_vjp/jvps
Does the following example help?

https://optax.readthedocs.io/en/latest/meta_learning.html

**Comment by pharringtonp19** [comment]
@mtthss  Thanks for the response 

Consider the toy example below -- I first posted this as a [discussion question in jax](https://github.com/google/jax/issues/8710), but realized that in order to provide the additional information that is requested, I needed to understand whether optax allows for custom vjp/jvp of update functions.

In short, when differentiating through a composition of functions, I would like to be able to replace an "intermediate" jacobian matrix with the identity matrix. As I show below, we can do this quite easily with custom jvp/vjps. 

The challenge I'm facing (which is not captured in this toy example) is how to define custom vjp/jvps when the intermediate function is actually an update function defined in optax. 

```
import jax 
import jax.numpy as jnp 
from jax import custom_vjp 

l = lambda x: jnp.cos(x)
g = lambda x: jnp.sin(x)
f = lambda x: jnp.tanh(x)
h = lambda x: f(g(l(x)))

x = 1.
print(f"Desired Gradient: {jax.grad(f)(g(l(x)))*jax.grad(l)(x)}")
print(f"Standard Jax Gradient: {jax.grad(h)(x)}")

Desired Gradient: -0.6529207229614258
Standard Jax Gradient: -0.559914231300354
```
Current Solution (although as @hawkinsp pointed out, `jvp` would be simpler here)
```
@custom_vjp 
def g(x):
  return jnp.sin(x)

def f_fwd(x):
  return g(x), (jnp.cos(x),)

def f_bwd(res, g):
  cos_x, = res 
  return (g,)

g.defvjp(f_fwd, f_bwd)

print(f"Standard Jax Gradient With Custom VJP: {jax.grad(h)(x)}")

Standard Jax Gradient With Custom VJP: -0.6529207229614258
```

**Comment by mtthss** [comment]
Would something like this be what you need

```python
opt = optax.adam(learning_rate=0.1)

@jax.custom_vjp 
def g(grads, state, params=None):
  return opt.update(grads, state, params)

def f_fwd(grads, state, params=None):
  return g(grads, state, params), (jnp.zeros_like(grads),)

def f_bwd(res, g):
  return (g,)

g.defvjp(f_fwd, f_bwd)

custom_opt = optax.GradientTransformation(
    init=opt.init,
    update=g,
)
```

**Comment by pharringtonp19** [comment]
@mtthss Thanks for the example and your further explanation. 

For some reason, I haven't been able to get an extension of your example to work, but it's likely because I am making a mistake somewhere on my end. I will keep playing around this example, and report back when I have found a solution.

```
import jax 
import jax.numpy as jnp 
import optax 

opt = optax.sgd(learning_rate=0.01)

@jax.custom_vjp 
def g(grads, state, params=None):
  return opt.update(grads, state, params)

def f_fwd(grads, state, params=None):
  return g(grads, state, params), (jnp.zeros_like(grads),)

def f_bwd(res, g):
  return (g,)

g.defvjp(f_fwd, f_bwd)

custom_opt = optax.GradientTransformation(
    init=opt.init,
    update=g,
)

def loss_fn(params):
  return jnp.reshape((params-2)**2, ())

params = jnp.array([1.])
opt_state = custom_opt.init(params)

def new_params(params, opt_state):
  grads = jax.grad(loss_fn)(params)
  updates, opt_state = custom_opt.update(grads, opt_state, params)
  params = optax.apply_updates(params, updates)
  return params

jax.jacrev(new_params, argnums=0)(params, opt_state)
```

**Comment by rosshemsley** [comment]
Hey @pharringtonp19, does the following solve your problem? (i.e. using `has_aux`?)

```
def f(grads):
  return (grads**2).sum(), (jnp.array([1,3,4]), jnp.array([5, 6, 7]))

jax.grad(f, has_aux=True)(1.0)
```
`(DeviceArray(2., dtype=float32), (DeviceArray([1, 3, 4], dtype=int32), DeviceArray([5, 6, 7], dtype=int32)))`

**Comment by pharringtonp19** [comment]
@rosshemsley I don't believe `has_aux` solves my problem. Since the function I am interested in differentiating is a vector-valued function, I have to use `jax.jacrev` instead of `jax.grad`, and `has_aux` is not yet implemented for `jax.jacrev` 

```
import jax 
import jax.numpy as jnp 
import optax 

opt = optax.sgd(learning_rate=0.01)

@jax.custom_vjp 
def g(grads, state, params=None):
  return opt.update(grads, state, params)

def f_fwd(grads, state, params=None):
  return g(grads, state, params), (jnp.zeros_like(grads),)

def f_bwd(res, g):
  return (g,)

g.defvjp(f_fwd, f_bwd)

custom_opt = optax.GradientTransformation(
    init=opt.init,
    update=g,
)

params = jnp.array([1.])
opt_state = custom_opt.init(params)
grads = jnp.ones_like(params)

jax.jacrev(g, has_aux=True)(grads, opt_state)
```

```TypeError: jacrev() got an unexpected keyword argument 'has_aux'```

**Comment by hawkinsp** [comment]
@pharringtonp19 Perhaps you are looking for `jax.vjp` instead of `jacrev`?

**Comment by rosshemsley** [comment]
Hey @pharringtonp19, did you manage to get optax to do what you wanted to do here?

I see you have some JAX questions, but for those it might be best to raise a ticket here https://github.com/google/jax/issues.
If you are happy to follow there, we can close this issue.

**Comment by pharringtonp19** [comment]
@rosshemsley I was hoping @hawkinsp might be able to clarify whether the issue that I am struggling with is a jax related issue or an optax related issue. I believe it is a jax related issue so I would be happy to close this for now, and re-open it if I find it to be an optax related one later on.

**Comment by hawkinsp** [comment]
@pharringtonp19 That sounds like a bug in your code to me.

**Comment by pharringtonp19** [comment]
@hawkinsp Thanks!

```
import jax 
import jax.numpy as jnp 
import optax 

opt = optax.sgd(learning_rate=0.01)

@jax.custom_vjp 
def g(grads, state, params=None):
  return opt.update(grads, state, params)

def f_fwd(grads, state, params=None):
  return g(grads, state, params), (jnp.zeros_like(grads),)

def f_bwd(res, g):
  return (g,)

g.defvjp(f_fwd, f_bwd)

custom_opt = optax.GradientTransformation(
    init=opt.init,
    update=g,
)

params = jnp.array([1.])
opt_state = custom_opt.init(params)
grads = jnp.ones_like(params)

#jax.jacrev(g, has_aux=True)(grads, opt_state)
param_updates, f_vjp, new_opt_state = jax.vjp(g, grads, opt_state, has_aux=True)
f_vjp(jnp.ones_like(param_updates))
```
