### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by gitfan7** [deepmind/optax#248]
Could anyone please fix the following error when running "import optax"? Thanks a lot.

ImportError: cannot import name 'apply_flat_fun' from 'jax.api_util' (/usr/local/lib/python3.7/dist-packages/jax/api_util.py)

**Comment by gitfan7** [comment]
Looking forward to hearing from you. Thanks a lot.

**Comment by mkunesch** [comment]
Hey! Thanks for the question! I couldn't reproduce the problem in a public colab when running `!pip install optax` and `import optax`. Could you provide more detail (perhaps the versions of libraries loaded would help reproduce the issue)?

**Comment by mkunesch** [comment]
Hi, I'll close this for now, but please feel free to reopen again if you still run into this issue or if you have more information to help me reproduce it. Thanks a lot!
