### ISSUE TITLE
Missing type hints

### ISSUE THREAD

**Issue by mkunesch** [deepmind/optax#250]
Some parts of optax do not yet have type hints. It would be great to add them! Files where I've found missing type hints include:

- [x] [utils.py](https://github.com/deepmind/optax/blob/master/optax/_src/utils.py)
- [x] [clipping.py](https://github.com/deepmind/optax/blob/master/optax/_src/clipping.py)
- [x] [linear_algebra.py](https://github.com/deepmind/optax/blob/master/optax/_src/linear_algebra.py)

but this list is not exhaustive. I'm marking this as "good first issue" - PRs that add missing type hints are greatly appreciated!

**Comment by esraa-saleh** [comment]
I would love to start working on this! Has someone been assigned already for all tasks?

**Comment by mkunesch** [comment]
Hi, that would be great! Nobody has been assigned yet so your contribution would be very welcome.
Thanks a lot and let me know if you have any questions!

**Comment by esraa-saleh** [comment]
Great! I'll start working on this then, and come back with questions if any come up :)

**Comment by yulonglin** [comment]
I'm adding another list of files with missing type hints. I'll work on them and add more files along the way :)
- [ ] [base.py](https://github.com/deepmind/optax/blob/master/optax/_src/base.py)
- [ ] [base_test.py](https://github.com/deepmind/optax/blob/master/optax/_src/base_test.py)

**Comment by Warlord-K** [comment]
> I'm adding another list of files with missing type hints. I'll work on them and add more files along the way :)
> 
> * [ ]  [base.py](https://github.com/deepmind/optax/blob/master/optax/_src/base.py)
> * [ ]  [base_test.py](https://github.com/deepmind/optax/blob/master/optax/_src/base_test.py)

I opened these and found that these files have type hints. So, I think this issue can be closed. Thanks

**Comment by hbq1** [comment]
Update: https://github.com/deepmind/optax/pull/413 has added missing type hints to linear_algebra.py.

**Comment by hbq1** [comment]
@mkunesch should we close this issue now?

**Comment by mkunesch** [comment]
Ah yes, thanks - this is done so let's close it for now - anyone who finds missing type hints is still welcome to file a PR to fix them of course!
