### ISSUE TITLE
Implement FastAdaBelief?

### ISSUE THREAD

**Issue by evanatyourservice** [deepmind/optax#280]
Hello! There is a newish paper improving upon AdaBelief, [FastAdaBelief](https://arxiv.org/abs/2104.13790), which is more or less a combination of AdaBelief and SAdam. So far it does seem to match the performance it promises in its paper in my experiments, and it has time-dependent epsilon and time-dependent beta2 so there is only one hyperparameter -- beta1. I have [implemented it here](https://github.com/evanatyourservice/FastAdaBelief-optax). If you'd like to add this to optax I'd be happy to do a pull request.

**Comment by carlosgmartin** [comment]
@evanatyourservice I'm also interested in this. Would you still like to submit a PR?

**Comment by evanatyourservice** [comment]
Hey Carlos! Iirc my implementation I posted is a little off from their paper, but when I implemented it correctly it didn’t really stand up to the test of time so to speak, adabelief alone is a much better optimizer :)

**Comment by carlosgmartin** [comment]
Interesting. The [paper](https://arxiv.org/abs/2104.13790)'s experiments show FastAdaBelief outperforming AdaBelief. Your experiments yielded the opposite result?

**Comment by evanatyourservice** [comment]
Yeah I remember finding something wrong with my implementation but then after I fixed it it still wasn’t holding up to some tests. I totally forget what I tested it on, probably vision and time series back then, but definitely worth checking out if you want! I’ll make sure my implementation above is updated to the paper. 

Interestingly the adabelief author made a new optimizer called acprop, could be worth checking out too

**Comment by evanatyourservice** [comment]
Ah I just realized I didn’t put my fastadabelief implementation public, I’ll post it on GitHub hopefully tonight. Maybe we should test it a little before suggesting optax add it. I’ll also add an acprop repo. I liked the theory behind acprop I think it would def be worth a PR

**Comment by carlosgmartin** [comment]
That sounds great!

**Comment by evanatyourservice** [comment]
@carlosgmartin sorry carlos i actually probably won't have time to get to this!

**Comment by carlosgmartin** [comment]
No worries! I can do it: https://github.com/google-deepmind/optax/issues/965.
