### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'FrozenDict'

### ISSUE THREAD

**Issue by tempdeltavalue** [deepmind/optax#291]
I used a bit modified model from JAX annotated mnist example 

```
def loss(preds, targets):
    out = jnp.mean((preds - targets)**2)
    return out

opt = optax.adam(learning_rate=0.003) 
opt_state = opt.init(params)

... 

grads = jax.grad(loss)(preds, y)
updates, opt_state = opt.update(grads, opt_state)   <--- Error here !
```

grads looks like this and have shape (1, 224, 224, 1)  (additional question why gradients have shape of input, I thought it should be shape of all params or something like that) and model's params is Frozen dict )
[[[[1.4224441e-05]
   [1.2348691e-05]
   [1.4693377e-05]
   ...
   [9.6913773e-06]
   [9.5350642e-06]
   [1.0785565e-05]]

some logs 

TypeError                                 Traceback (most recent call last)
<ipython-input-18-c904b5ea1abe> in <module>()
     26     print(grads.shape)
     27 
---> 28     updates, opt_state = opt.update(grads, opt_state)
     29     params = optax.apply_updates(params, updates)
     30 

5 frames
/usr/local/lib/python3.7/dist-packages/optax/_src/combine.py in update_fn(updates, state, params)
     52     new_state = []
     53     for s, fn in zip(state, update_fns):
---> 54       updates, new_s = fn(updates, s, params)
     55       new_state.append(new_s)
     56     return updates, tuple(new_state)

/usr/local/lib/python3.7/dist-packages/optax/_src/transform.py in update_fn(***failed resolving arguments***)
    300   def update_fn(updates, state, params=None):
    301     del params
--> 302     mu = _update_moment(updates, state.mu, b1, 1)
    303     nu = _update_moment(updates, state.nu, b2, 2)
    304     count_inc = numerics.safe_int32_increment(state.count)

/usr/local/lib/python3.7/dist-packages/optax/_src/transform.py in _update_moment(updates, moments, decay, order)
     79   """Compute the exponential moving average of the `order-th` moment."""
     80   return jax.tree_multimap(
---> 81       lambda g, t: (1 - decay) * (g ** order) + decay * t, updates, moments)
     82 
     83 

/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py in tree_map(f, tree, is_leaf, *rest)
    176   leaves, treedef = tree_flatten(tree, is_leaf)
    177   all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 178   return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
    179 
    180 tree_multimap = tree_map

/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py in <genexpr>(.0)
    176   leaves, treedef = tree_flatten(tree, is_leaf)
    177   all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 178   return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
    179 
    180 tree_multimap = tree_map

/usr/local/lib/python3.7/dist-packages/optax/_src/transform.py in <lambda>(g, t)
     79   """Compute the exponential moving average of the `order-th` moment."""
     80   return jax.tree_multimap(
---> 81       lambda g, t: (1 - decay) * (g ** order) + decay * t, updates, moments)
     82 
     83 

TypeError: unsupported operand type(s) for *: 'float' and 'FrozenDict'

**Comment by tempdeltavalue** [comment]
My mistake in grad and loss func sorry

**Comment by mhr** [comment]
Hey, what was the solution?

**Comment by tempdeltavalue** [comment]
@mhr 
Sorry for delay ... )
I change my loss to something like that  (looks like you cannot pass model inside loss)

def loss(params, targets):
    gausses = apply(params, targets)

    out = jnp.mean((gausses - targets)**2)
    return out
