### ISSUE TITLE
docs: loss functions not rendering properly

### ISSUE THREAD

**Issue by grahamgower** [deepmind/optax#317]
Compare https://optax.readthedocs.io/en/latest/api.html#losses with https://optax.readthedocs.io/en/stable/api.html#losses

api.rst has a bug in the autofunction syntax for `ctc_loss`, so docs for ctc_loss and subsequent loss functions aren't rendered.
https://github.com/deepmind/optax/blob/252d152660300fc7fe22d214c5adbe75ffab0c4a/docs/api.rst#L445-L456

**Comment by mkunesch** [comment]
Oh, thanks a lot for raising this! Would you like to file a PR with a fix? If not, I'm also happy to do it - just want to make sure we don't duplicate the work.

Thanks a lot again!
