### ISSUE TITLE
`_bias_correction` forces recompilation of `integer_pow`

### ISSUE THREAD

**Issue by epignatelli** [deepmind/optax#328]
This might be related to #197, but I don't have enough knowledge to confirm it.

In short, while using `optax` with `flax.linen`, `optimizer.update` forces jit-recompilation of the `integer_pow` jax primitive.
I get these results on a GPU backend.

```python
from functools import partial
import jax
import jax.numpy as jnp
import optax
from flax import linen as nn
from jax.config import config
import os


config.update("jax_log_compiles", 1)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"


def biascorrection_recompilation_test():
    class M(nn.Module):
        @nn.compact
        def __call__(self, x):
            x = nn.Dense(1)(x)
            return x

    m = M()
    o = optax.adam(0.025, b1=int(1))

    input_array = jnp.ones((8,), dtype=float)
    params = m.init(jax.random.PRNGKey(0), input_array)
    opt_state = o.init(params)

    m_forward = jax.vmap(m.apply, in_axes=(None, 0))

    @jax.jit
    @partial(jax.value_and_grad, has_aux=True)
    def loss_fn(params, x, y):
        params_m = params
        y_m = m_forward(params_m, x)
        loss = jnp.mean(y_m - y ** 2)
        return loss, ()



    for i in range(1000):
        print(i)
        inputs = jax.random.normal(jax.random.PRNGKey(i), (32, 8))
        outputs = jax.random.normal(jax.random.PRNGKey(-i), (32, 8))
        (loss, aux), grads = loss_fn(params, inputs, outputs)
        updates, opt_state = o.update(grads, opt_state)
        params = optax.apply_updates(params, updates)


if __name__ == "__main__":
    biascorrection_recompilation_test()

```
At each `i`:
```
WARNING:absl:Finished tracing + transforming prim_fun for jit in 0.00016188621520996094 sec
WARNING:absl:Compiling prim_fun (140402616089792 for args (ShapedArray(float32[], weak_type=True),).
WARNING:absl:Finished XLA compilation of integer_pow in 0.02527928352355957 sec
```

Where `prim_fun` refers the `integer_pow` op at this line:
https://github.com/deepmind/optax/blob/b4aa6657bbf79985279dea76eaf6d53b25d7e8d9/optax/_src/transform.py#L105

#329 does remove the issue by replacing the call to`integer_pow` with `pow`, but I am not sure this is the direction you would like to take.

**Comment by rosshemsley** [comment]
Hello @epignatelli,

I am not totally sure why the recompilation is happening on every step (for integer pow) - although, this should not happen if you jit the the full update function, and apply that jitted function in every loop iteration.

e.g.

```python
def update_fn(params, inputs)

    @partial(jax.value_and_grad, has_aux=True)
    def loss_fn(params, x, y):
        params_m = params
        y_m = m_forward(params_m, x)
        loss = jnp.mean(y_m - y ** 2)
        return loss, ()

    (loss, aux), grads = loss_fn(params, inputs, outputs)
    updates, opt_state = o.update(grads, opt_state)
    params = optax.apply_updates(params, updates)
    return params


update_fn = jax.jit(update_fn)

for i in range(1000):
    print(i)
    inputs = jax.random.normal(jax.random.PRNGKey(i), (32, 8))
    outputs = jax.random.normal(jax.random.PRNGKey(-i), (32, 8))
```

**Comment by rosshemsley** [comment]
@hbq1 suggests that the recompilation for interger_pow may be happening because the exponent is a static argument for integer pow. This would be because more efficient algorithms exist when the exponent is a known integer.

Does the above help?

**Comment by hbq1** [comment]
Indeed, [the docs](http://google3/third_party/py/jax/_src/lax/lax.py;l=362;rcl=442675847) state that the exponent in `integer_pow` is a _fixed_ integer.

**Comment by NeilGirdhar** [comment]
(I just checked, and this is not related to #197 as much as I wish it were.)

**Comment by epignatelli** [comment]
HI @rosshemsley, thanks for the directions! And apologies for the delayed response, I have been away.

I tested the code with a fully jitted update function.
The main difference for the purpose of recompilation is that when jitting the update function `count` is a `Traced<ShapedArray>`, instead of a `DeviceArray`.

Some details:
- Exponentiation for `DeviceArray` hits the `lax.integer_pow` primitive.
- Exponentiation for `Traced<ShapedArray>` hits the `jax.core.Tracer.__rpow__` primitive.

On a different note, when not jitting the full update function, recompiling `integer_pow` at each iteration seems more expensive than calling `pow`.
Computational times for this function, five runs and 1000 iterations per run, measures in seconds.

| Branch 	| Avg      	| Std       	| 1                 	| 2                 	| 3                	| 4                 	| 5                 	|
|--------	|----------	|-----------	|-------------------	|-------------------	|------------------	|-------------------	|-------------------	|
| master 	| 72.08428 	| 2.1065526 	| 68.44841027259827 	| 71.01362156867981 	| 73.1131432056427 	| 73.90358185768127 	| 73.94265246391296 	|
| #329   	| 3.465429 	| 0.3372677 	| 4.1398454         	| 3.29095           	| 3.2909377        	| 3.3082917         	| 3.2971206         	|


```python
def biascorrection_recompilation_test():
    class M(nn.Module):
        @nn.compact
        def __call__(self, x):
            x = nn.Dense(1)(x)
            return x

    m = M()
    o = optax.adam(0.025, b1=int(1))

    input_array = jnp.ones((8,), dtype=float)
    params = m.init(jax.random.PRNGKey(0), input_array)
    opt_state = o.init(params)

    m_forward = jax.vmap(m.apply, in_axes=(None, 0))

    @jax.jit
    @partial(jax.value_and_grad, has_aux=True)
    def loss_fn(params, x, y):
        params_m = params
        y_m = m_forward(params_m, x)
        loss = jnp.mean(y_m - y ** 2)
        return loss, ()

    start = time.time()
    for i in range(1000):
        print(i)
        inputs = jax.random.normal(jax.random.PRNGKey(i), (32, 8))
        outputs = jax.random.normal(jax.random.PRNGKey(-i), (32, 8))
        _, grads = loss_fn(params, inputs, outputs)
        updates, opt_state = o.update(grads, opt_state)
        params = optax.apply_updates(params, updates)
    print(time.time() - start)
```

**Comment by epignatelli** [comment]
Guys, any idea on the status of this?

**Comment by hbq1** [comment]
@epignatelli is this issue still relevant or should we close it?

**Comment by epignatelli** [comment]
Hi @hbq1 -- sorry for the big delay.
Let me re-test this today and will get feed back into the conversation.

**Comment by epignatelli** [comment]
@hbq1 I can confirm that the behaviour w/o fully jitting the update function is still the same, i.e., xla is recompiling `pow_integer` of any new exponent.

If we fully jitted update function and follow the same benchmark above, we get the following results, in seconds.

On `master`: 
- Runs `[1.8947148323059082, 1.6692390441894531, 1.6632952690124512, 1.666994333267212, 1.6678147315979004]`
- Mean `1.7124115`
- Mean excluding first hit `1.6668358`
- Std `0.091172755`
- Std excluding first hit `0.0021962684`

On https://github.com/deepmind/optax/pull/329:
- Runs `[1.9085335731506348, 1.6419365406036377, 1.6377665996551514, 1.657588243484497, 1.6615831851959229]`
- Mean `1.7014817`
- Mean excluding first hit `1.6497186`
- Std `0.1039175`
- Std excluding first hit `0.010076091`

Results are quite similar, although, the issue w/o jitting reimans, and jitting the full update function might not depend on the user in some cases.

**Comment by epignatelli** [comment]
Thanks @hbq1, I just reopened #329 in case you decide to merge up.

**Comment by hbq1** [comment]
Hi @epignatelli, it tuned out that casting the denominator to `t.dtype` resulted in numerical instabilities in half-precision arithmetic, so your original PR was rolled back. We came up with a different solution that solves both issues, see #448.

**Comment by epignatelli** [comment]
Hi @hbq1, so sorry about this -- the solution makes very much sense.
Thanks very much for pinging me!
