### ISSUE TITLE
adamax and adamaxw not exposed.

### ISSUE THREAD

**Issue by nasyxx** [deepmind/optax#429]
adamax and adamaxw not exposed

I noticed that optax did not expose `adamax` and `adamaxw` defined in `_src/alias.py` (https://github.com/deepmind/optax/blob/2df58b4f85055f69ffbc12d9f0eddbe6edf5a740/optax/_src/alias.py#L703-L776) in `__init__.py`. Is this done on purpose because they have some problems? Or just missed it?

**Comment by hbq1** [comment]
Hi @nasyxx, this is a great catch, thank you! 
Would you like to send a PR which would expose these functions?

**Comment by nasyxx** [comment]
> Would you like to send a PR which would expose these functions?

Hi, sure.  It's #433
