### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by xinglong-li** [deepmind/optax#453]
In the environment:
jax.__version__ = 0.3.24
and jaxlib.__version__ = 0.3.24,
and optax  0.1.3,

optax cannot be loaded, and 
'import optax' raises following error:
AttributeError: module 'jax' has no attribute '_src'

**Comment by rosshemsley** [comment]
Hey @xinglong-li , I was unfortunately unable to reproduce this error. Here's the environment I tested with (on a macbook pro):

```
$ python --version
Python 3.8.2

$ pip freeze
absl-py==1.3.0
chex==0.1.5
dm-tree==0.1.7
jax==0.3.24
jaxlib==0.3.24
numpy==1.23.4
opt-einsum==3.3.0
optax==0.1.3
scipy==1.9.3
toolz==0.12.0
typing_extensions==4.4.0

$ python
>>> import optax
>>> # works
```

Do you have more details on how to reproduce this error?

**Comment by xinglong-li** [comment]
Hi @rosshemsley, thanks for your response, it seems this is a random bug maybe comes with Jax? 
It happened to me with python 3.9 on apple silicon m1 and python 3.10 on ubuntu 22.04. It disappeared once I upgraded Jax to 0.3.25.
