### ISSUE TITLE
`optax.inject_hyperparams` no longer works with the latest chex

### ISSUE THREAD

**Issue by vwxyzjn** [deepmind/optax#518]
Hi thanks for the useful package! `optax.inject_hyperparams` no longer works with the latest chex. See

```pip install optax==0.1.4 chex==0.1.7 && python -c "import optax;optax.inject_hyperparams(optax.adamw)(learning_rate=0.123)"```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/admin/home-costa/.cache/pypoetry/virtualenvs/cleanba-nnQq3SJr-py3.8/lib/python3.8/site-packages/optax/_src/schedule.py", line 580, in wrapped_transform
    elif isinstance(value, (int, float, chex.Array)):
  File "/usr/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

I have raised a related issue in https://github.com/deepmind/chex/issues/261

**Comment by terrykong** [comment]
I have run into this as well. Looks like the two straightforward options are:

1. to bump the [python requirement](https://github.com/deepmind/optax/blob/master/setup.py#L61) or 
2. just list out the types defined by a chex.Array, i.e.:
```
isinstance(value, (int, float, chex.ArrayDevice, chex.ArrayNumpy, chex.ArrayBatched, chex.ArraySharded, np.bool_, np.number))
```

The former might cut off some users if they need py3.8 and the latter is brittle if chex decides to define an Array differently. I can make a PR if there is any guidance from the optax team.

**Comment by vwxyzjn** [comment]
Btw currently a quick hack is to downgrade `chex==0.1.5`

**Comment by hbq1** [comment]
Optax [v0.1.5](https://github.com/deepmind/optax/releases/tag/v0.1.5) has been just released 🎉 
Updating to this new version should resolve these errors.
