### ISSUE TITLE
Prevent creating unnecessary momentum variables

### ISSUE THREAD

**Issue by n2cholas** [deepmind/optax#52]
Currently, `optax.sgd` and `optax.noisy_sgd` unconditionally create momentum variables for the parameters, since both rely on `trace`. For `optax.noisy_sgd`, this is unnecessary since `decay` is always `0`. For `optax.sgd`, this is unexpected since `momentum=0` by default (and can be wasteful for large models). 

`optax.noisy_sgd` should only require `_scale_by_learning_rate` (with a negation). `optax.sgd` could conditionally add `trace` if `momentum > 0`. 

Below are the lines of code I'm referring to:

https://github.com/deepmind/optax/blob/ba0bc11d172054d65b4387ecae840c04e2bc7035/optax/_src/alias.py#L142-L148

https://github.com/deepmind/optax/blob/ba0bc11d172054d65b4387ecae840c04e2bc7035/optax/_src/alias.py#L105-L113

And here's where trace automatically creates it's state:

https://github.com/deepmind/optax/blob/ba0bc11d172054d65b4387ecae840c04e2bc7035/optax/_src/transform.py#L212-L213

**Comment by mtthss** [comment]
Good point!

Yeah `optax.noisy_sgd` should just be
```
def noisy_sgd(learning_rate: ScalarOrSchedule, 
               eta: float = 0.01, 
               gamma: float = 0.55, 
               seed: int = 0) -> GradientTransformation: 
   return combine.chain( 
       _scale_by_learning_rate(learning_rate), 
       transform.add_noise(eta, gamma, seed), 
   ) 
```

**Comment by mtthss** [comment]
And you are right for `optax.sgd` we could check whether momentum > 0 and skip the trace when this is not the case

**Comment by mtthss** [comment]
Do you want to put together a PR?

**Comment by n2cholas** [comment]
Sure!
