### ISSUE TITLE
Latest release raises errors with JAX's latest release

### ISSUE THREAD

**Issue by albcab** [deepmind/optax#522]
JAX subsumed `DeviceArray`, `ShardedDeviceArray`, and `GlobalDeviceArray` types into the unified `Array` type. Their latest release raises and error when using any of the deprecated types. Optax's latest developments use the new `jax.Array` but the latest release still uses the deprecated types. 

In blackjax we use optax as a dependency, thus needing to either downgrade JAX or use the latest developments of optax instead of the latest release. But we can't publish to pypi with the latest developments as a dependency (see [#521](https://github.com/blackjax-devs/blackjax/issues/521)). Is there any chance you could cut a new release that works with the latest version of JAX? Or maybe publish a "nightly" version of the library to pypi?

Thanks for the help (and the library) :smile:

**Comment by hbq1** [comment]
Hi @albcab, optax [v0.1.5](https://github.com/deepmind/optax/releases/tag/v0.1.5) has been just released 🎉 

Feel free to re-open the issue if you still see those errors.
