### ISSUE TITLE
optax.MultiSteps memory consumption

### ISSUE THREAD

**Issue by albertogaspar** [deepmind/optax#528]
When using `optax.MultiSteps` (vs not using the MultiSteps wrapper) is there an overhead memory consumption equal to the size of the model's parameters? 

I am asking this cause I see that in the [`init` method](https://github.com/deepmind/optax/blob/e5f910e92534c3b444e806582227389b7bb2b3b0/optax/_src/wrappers.py#L353) a new array of zeros (with the same shape of model's `params`) is created in order to keep track of the accumulated gradients over multiple steps.

**Comment by hbq1** [comment]
Hi @albertogaspar, yes, your understanding is correct: `optax.MultiSteps` accumulates intermediate gradients in a buffer of the same size as parameters. This buffer is a part of the wrapper's state.
