### ISSUE TITLE
Implement scaling by AdaBelief

### ISSUE THREAD

**Issue by mtthss** [deepmind/optax#6]
See paper:

https://arxiv.org/abs/2010.07468

This should be a trivial modification of the existing `scale_by_adam` transform.

**Comment by joaogui1** [comment]
I would like to implement this issue!

**Comment by mtthss** [comment]
Awesome! Looking forward to your contribution!

Couple of suggestions:

Please move the bias correction code out of scale_by_adam into a standalone fn:

```
def _bias_correction(moment, decay, count):
  """Perform bias correction. This becomes a no-op as count goes to infinity."""
  bias_correction = 1 - decay**count
  return jax.tree_map(lambda t: t / bias_correction.astype(t.dtype), moment)
```

Then add both a `scale_by_belief` in `transform.py` and a `adabelief` optimiser in `alias.py`.

Thanks!

**Comment by mtthss** [comment]
Thanks @joaogui1 !

**Comment by mtthss** [comment]
We had to briefly revert the change since there was a merging issue,
your PR has now been resubmitted (still with you as author).

**Comment by 8bitmp3** [comment]
AdaBelief has been documented https://github.com/deepmind/optax/pull/83 thanks everyone 👍
